### Register user
POST http://localhost:5252/register
Content-Type: application/json

{
  "Username": "username123",
  "Password": "password"
}

### Create user
POST http://localhost:5252/users
Content-Type: application/json

{
  "Username": "username123",
  "Password": "password"
}

### Login user
POST http://localhost:5252/login
Content-Type: application/json

{
  "Username": "username1231",
  "Password": "password"
}
